###
POST http://localhost:8080/admin/reset


###
POST http://localhost:8080/api/validate_chirp 
Content-Type:  application/json

{
  "body": "I had something interesting for breakfast"
}

###
POST http://localhost:8080/api/validate_chirp 
Content-Type:  application/json

{
  "body": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
}

###
POST http://localhost:8080/api/validate_chirp
Content-Type:  application/json

{
  "body": "I really need a kerfuffle to go to bed sooner, Fornax !"
}

###
POST http://localhost:8080/api/chirps
Content-Type:  application/json

{
  "body": "I hear Mastodon is better than Chirpy. sharbert I need to migrate",
  "userId": "8fb16d42-9c1a-4ae0-95b0-e8c24af35de6"
}

###
GET http://localhost:8080/api/generateNotFoundError

###
POST http://localhost:8080/api/users
Content-Type:  application/json

{
  "email": "alangton1337@gmail.com"
}



###
GET http://localhost:8080/api/chirps

###
GET http://localhost:8080/api/chirps/03e937f4-3fcd-4a36-8081-a8242d54cfe7